org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

mod_id=occultengineering
mod_name=Create: Occult Engineering
mod_license=MIT
mod_version=0.9.1
mod_group_id=io.github.irishgreencitrus
mod_authors=irishgreencitrus
mod_description=An addon mod that adds some automation between Occultism and Create

neo_version=21.1.219
neo_version_range=[21.0.110-beta,)
neo_loader_version_range=[3,)
mdg_version=2.0.105
minecraft_version_major=1.21
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.4)

occultism_version=1.215.0

jei_minecraft_version=1.21.1
jei_version=19.8.2.99

create_minecraft_version=1.21.1
flywheel_minecraft_version=1.21.1

create_version=6.0.10-280
ponder_version=1.0.82

flywheel_version=1.0.6
flywheel_version_range=[1.0.0,2.0)

registrate_version=MC1.21-1.3.0+67

# Create and Occultism both depend on these, so we need them too.
curios_version=9.5.1
curios_version_range=[9.5.1,)

geckolib_version=4.6.6
geckolib_version_range=[4.5.5,)

smartbrainlib_version=1.16.1
smartbrainlib_version_range=[1.14.5,)

# Modonomicon version is dependent on Occultism's version
modonomicon_version=1.108.5
modonomicon_version_range=[1.106.0,)

parchment_version=2024.11.17